spring:
  application:
    name: flownews

  jpa:
    show-sql: false

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRESQL_URI}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,https://sijeom.kr}

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google-mobile:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        base-uri: ${FRONTEND_URL:https://sijeom.kr}

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
      chat:
        options:
          model: gpt-4o

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hour in milliseconds
app:
  mobile:
    scheme: sijeom

recommendation:
  api:
    url: ${RECOMMENDATION_API_URL}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true

server:
  port: ${PORT:8080}
  forward-headers-strategy: framework
  tomcat:
    use-relative-redirects: true
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For